FROM python:3.10.11

# Install the libgl1 package required by OpenCV
RUN apt-get update && apt-get install -y libgl1 && rm -rf /var/lib/apt/lists/*
COPY yolov5 /app/yolov5
COPY . /app
WORKDIR /app

RUN pip install --no-cache-dir -r yolov5/requirements.txt

RUN pip install --no-cache-dir flask gunicorn torchvision torch mediapipe pillow numpy

EXPOSE 8000

CMD ["gunicorn", "--workers=4", "-b", "0.0.0.0:8000", "app:app"]
